### ISSUE TITLE
Uncaught syntax error in embed.js on blog post causes noticeable CPU load and frozen tab

### ISSUE THREAD

**Issue by zyzzyxdonta** [thechangelog/changelog.com#466] opened 2023-06-04 19:23 UTC
Hi,

I just came across [this blog post](https://changelog.com/posts/git-is-simply-too-hard) on lobste.rs and noticed a sudden increase in CPU load while reading. Opening the browser console revealed hundreds of thousands of uncaught syntax errors. This seems to happen on any other page under /posts/, as well.

![Screenshot_20230604_211259](https://github.com/thechangelog/changelog.com/assets/15108787/9bc48605-2e89-4dd6-b469-89a0ad21a881)

Browser is Firefox 113.0.1 on Fedora.

**Comment by jerodsanto** [comment] 2023-06-04 19:39
Super weird, sorry about that! I can't reproduce in Firefox, Safari or Chrome. Perhaps noteworthy is we use Turoblinks so page navigations don't do full reloads. A few questions:

1.  Did you engage with the embedded player at all? Hit play or anything?
2. Did you land directly on the page or navigate to it? 
3. Can you perform a full refresh and see if the embed error reoccurs?

I can easily fix this by loading the iframe on the page directly vs using our embed code, but that'd be treating the symptom and I'd love to know the cause first...

**Comment by zyzzyxdonta** [comment] 2023-06-04 20:05
1. I did not interact with the player. I didn't even click the "Click here to listen along" link that opens the player. The problem persists if I do.
2. I landed on the page directly. Navigating to it causes the same problem.
3. I reloaded the page with deactivated cache and the problem persists.

**Comment by jerodsanto** [comment] 2023-06-05 14:45
Well I'm stumped. I upgraded to Firefox 113.0.2 on Mac and still don't see any errors. I also asked in our Slack and a couple others confirmed the same (one running Linux, albeit version 110).

Could there be a bug in the `JSON.parse` for your specific Firefox on Fedora? Doubtful, I admit. More likely it's an extension or security flag you have set that's running interference.

Either way, there is no real reason to use your own embed script on the site. We can just directly insert the iframe into the content of the post. I'll probably do that and close this issue. BUT my fear is that embeds are broken on other people's sites for you as well, which would not be cool.

If you don't mind checking, do you also get the error here?  https://plausible.io/blog/changelog-podcast

**Comment by zyzzyxdonta** [comment] 2023-06-05 16:36
OK, so the error goes away if I disable the extension "DuckDuckGo Privacy Essentials"! I guess something is mistaken as a tracker and blocked.

Here is a screenshot of what is passed to `JSON.parse` with the extension enabled:

![Screenshot_20230605_183310](https://github.com/thechangelog/changelog.com/assets/15108787/7664a727-b2e8-4711-97ed-6a87c85af714)

**Comment by jerodsanto** [comment] 2023-06-05 20:57
I can't think of any reasons why Plausible requests would break the embed. I went ahead and switched this to an iframe embed instead of a JS one. Like I said, no reason to use JS to load the iframe on our own site. Thanks for the report, happy hacking!

**Closed by jerodsanto** 2023-06-05 20:57 UTC
Labels: bug
