### ISSUE TITLE
Captcha Error

### ISSUE THREAD

**Issue by AdabanyaChinedu** [thechangelog/changelog.com#341] opened 2020-12-28 12:23 UTC
I'm trying to signup on changelog via https://changelog.com/join on chrome browser, after filling the required fields and pressed the button "Join Now", I got a  "CAPTCHA fail. Are you blocking scripts? Are you a robot? 🤖" orange background flash message.

![image](https://user-images.githubusercontent.com/45187095/103214059-c5fd9700-490f-11eb-89a5-35240c8e1c03.png)

**Comment by AdabanyaChinedu** [comment] 2020-12-28 12:33
It works fine on Edge and Firefox browser.

**Comment by sleepiejohn** [comment] 2021-01-06 15:36
Indeed 

* Happens on Chrome (mine at `87.0.4280.88`)
* Disabled uBlock after receiving the error and I have tried again
* Got the following at the console (couldn't copy and paste)

![image](https://user-images.githubusercontent.com/5256711/103786312-10bb9500-501b-11eb-8e1e-40c43997598d.png)

The learn more link sends you to [here](https://developers.google.com/web/fundamentals/security/csp) in case it helps.

**Comment by jerodsanto** [comment] 2021-01-06 15:47
Thanks for the report. 😢 

I'm generally pretty disappointed with this Captcha setup and would love an alternative solution if anybody has a bright idea!

Spammers have defeated all of my previous attempts:

- Require JavaScript for form submission
- Add a field that is hidden by CSS so humans won't fill it in
- Require email confirmation (this has been historically bullet proof until recently)

Maybe some kind of simpler, hand-rolled captcha would be better?

**Comment by sleepiejohn** [comment] 2021-01-09 20:51
The problem seems to be with chrome enforcing the Content Security Policy on that version, and not hCaptcha.

I tried to reproduce the issue today but could not, if I disable uBlock it works as expected. But the version of chrome is now ` 87.0.4280.141` from `87.0.4280.88`. Who knows what they have done 🤷🏻 

I found documentation about the CSP configuration for hCaptcha in case it reapears, [here](https://docs.hcaptcha.com/#content-security-policy-settings)

**Comment by jordie23** [comment] 2021-03-15 22:58
I have the issue on any browser I try. Chrome on Mac OS `89.0.4389.82`, Firefox on Mac OS `85.0.2` also Safari on iPhone `14.4`.

I updated Firefox to `86.0.1` and it works.

@jerodsanto Have you tried google's recaptcha ? https://www.google.com/recaptcha/about/ Or is there a reason you're avoiding that option?

**Comment by jerodsanto** [comment] 2021-03-17 16:05
I'm specifically avoiding Google because they already capture enough data in the world and I'd like to contribute less to that effort.

That being said, this current solution has been a BIG headache for many people and I'd love to replace it with something different if anyone has good ideas on the matter 🙏

**Comment by jerodsanto** [comment] 2022-03-07 19:34
We've changed this implementation quite a bit since the initial bug was reported, so I'm closing for now and hope someone opens a fresh one if it's still a problem ✊

**Closed by jerodsanto** 2022-03-07 19:34 UTC
Labels: bug
